worker_processes 4;
events { worker_connections 4096; }
http {
    access_log off;
    server {
        listen 8080;
        root /app/public;
        location / {
            fastcgi_pass 127.0.0.1:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        }
    }
}
